sudo: required

language: python

services:
- docker

os: linux
dist: trusty

matrix:
  include:
  - env: PYENV=2.7.14
  - env: PYENV=3.3.7
  - env: PYENV=3.4.7
  - env: PYENV=3.5.4
  - env: PYENV=3.6.3

install:
- pip install coveralls # Need to have coveralls installed locally for after_success to run

script:
- >
  docker run
  -v $(pwd):$(pwd)
  -w $(pwd)
  -e PYENV=$PYENV
  -e KERBEROS_USERNAME=administrator
  -e KERBEROS_PASSWORD=Password01
  -e KERBEROS_REALM=example.com
  ubuntu:16.04
  /bin/bash .travis.sh

after_success:
- coveralls
